### ISSUE TITLE
初始化项目失败

### ISSUE THREAD

**Issue by zhangwei1011** [yeild/react-template-webpack#1]
nternal/child_process.js:328
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1020:11)
    at ChildProcess.spawn (internal/child_process.js:328:11)
    at exports.spawn (child_process.js:369:9)
    at Command.executeSubCommand (/usr/local/lib/node_modules/init-react/node_modules/commander/index.js:564:14)
    at Command.parse (/usr/local/lib/node_modules/init-react/node_modules/commander/index.js:489:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/init-react/bin/react:7:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

**Comment by yeild** [comment]
看起来像是没有权限
